export const ADD_TOKEN = 'ADD_TOKEN'
export const ADD_TOKEN_SUCCESSFUL = 'ADD_TOKEN_SUCCESSFUL'
export const ADD_TOKEN_FAIL = 'ADD_TOKEN_FAIL'

export const REMOVE_TOKEN = 'REMOVE_TOKEN'
export const REMOVE_TOKEN_SUCCESSFUL = 'REMOVE_TOKEN_SUCCESSFUL'
export const REMOVE_TOKEN_FAIL = 'REMOVE_TOKEN_FAIL'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const GET_INCOME = 'GET_INCOME'
export const GET_INCOME_SUCCESSFUL = 'GET_INCOME_SUCCESSFUL'
export const GET_INCOME_FAIL = 'GET_INCOME_FAIL'

export const ADD_INCOME = 'ADD_INCOME'
export const ADD_INCOME_SUCCESSFUL = 'ADD_INCOME_SUCCESSFUL'
export const ADD_INCOME_FAIL = 'ADD_INCOME_FAIL'

export const REMOVE_INCOME = 'REMOVE_INCOME'
export const REMOVE_INCOME_SUCCESSFUL = 'REMOVE_INCOME_SUCCESSFUL'
export const REMOVE_INCOME_FAIL = 'REMOVE_INCOME_FAIL'

export const GET_EXPENSES = 'GET_EXPENSES'
export const GET_EXPENSES_SUCCESSFUL = 'GET_EXPENSES_SUCCESSFUL'
export const GET_EXPENSES_FAIL = 'GET_EXPENSES_FAIL'

export const ADD_EXPENSES = 'ADD_EXPENSES'
export const ADD_EXPENSES_SUCCESSFUL = 'ADD_EXPENSES_SUCCESSFUL'
export const ADD_EXPENSES_FAIL = 'ADD_EXPENSES_FAIL'

export const REMOVE_EXPENSES = 'REMOVE_EXPENSES'
export const REMOVE_EXPENSES_SUCCESSFUL = 'REMOVE_EXPENSES_SUCCESSFUL'
export const REMOVE_EXPENSES_FAIL = 'REMOVE_EXPENSES_FAIL'

export const DATE_FILTER = 'DATE_FILTER'
export const DATE_FILTER_SUCCESSFUL = 'DATE_FILTER_SUCCESSFUL'
export const DATE_FILTER_FAIL = 'DATE_FILTER_FAIL'


export const CHECK_TOKEN = 'CHECK_TOKEN'